server:
  port: 8085

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/qr_manager
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

---
spring:
  application:
    name: qr_manager
  config:
    import: "optional:configserver:http://localhost:8088"

#eureka:
#  client:
#    serviceUrl:
#      defaultZond: http://localhost:8761/eureka/
